server:
  port: 8071
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Moligouan/BankAppu.git

  profiles:
    active: git